export const weapons = [
  {
    "id": "wpn_0",
    "sourceFile": "daoqi.md",
    "name": "鬼方9式“云外镜”铳型导器",
    "category": "导器",
    "range": "远程",
    "company": "西川霊術重工株式会社",
    "socialCredit": "III",
    "bonusSources": [
      "智力"
    ],
    "rawDamage": "1d12，辐射",
    "damageType": "",
    "armorPierceLevel": "",
    "size": 14,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "上品级",
    "rarityMinor": "A",
    "price": 250,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": true,
    "rawValue": "上品级A，250两"
  },
  {
    "id": "wpn_1",
    "sourceFile": "daoqi.md",
    "name": "鬼方7式“针女”铳型导器",
    "category": "导器",
    "range": "近程",
    "company": "西川霊術重工株式会社",
    "socialCredit": "III",
    "bonusSources": [
      "智力"
    ],
    "rawDamage": "1d4，X级穿刺（X等同于计入点数的牌和骰子的数量，最大6）",
    "damageType": "穿刺",
    "armorPierceLevel": "",
    "size": 16,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "上品级",
    "rarityMinor": "B",
    "price": 200,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": true,
    "rawValue": "上品级B，200两"
  },
  {
    "id": "wpn_2",
    "sourceFile": "daoqi.md",
    "name": "SN-101 “流素”杖型导器",
    "category": "导器",
    "range": "近程",
    "company": "新血股份有限公司",
    "socialCredit": "？",
    "bonusSources": [
      "灵性",
      "智力"
    ],
    "rawDamage": "2d8，3级以太",
    "damageType": "以太",
    "armorPierceLevel": 3,
    "size": 18,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "收藏级",
    "rarityMinor": "C",
    "price": 500,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": true,
    "rawValue": "收藏级C，500两"
  },
  {
    "id": "wpn_3",
    "sourceFile": "daoqi.md",
    "name": "SN-103 “静溪”匣型导器",
    "category": "导器",
    "range": "近程",
    "company": "新血股份有限公司",
    "socialCredit": "？",
    "bonusSources": [
      "灵性",
      "魅力"
    ],
    "rawDamage": "2d6，2级以太",
    "damageType": "以太",
    "armorPierceLevel": 2,
    "size": 12,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "收藏级",
    "rarityMinor": "C",
    "price": 550,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": true,
    "rawValue": "收藏级C，550两"
  },
  {
    "id": "wpn_4",
    "sourceFile": "daoqi.md",
    "name": "“行禅”杖型导器",
    "category": "导器",
    "range": "近程",
    "company": "天工峡集团",
    "socialCredit": "？",
    "bonusSources": [
      "魅力",
      "智力"
    ],
    "rawDamage": "2d6，3级炼金",
    "damageType": "炼金",
    "armorPierceLevel": 3,
    "size": 10,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "上品级",
    "rarityMinor": "A",
    "price": 200,
    "hasTactics": false,
    "hasAccessories": true,
    "hasExtraEffect": false,
    "rawValue": "上品级A，200两"
  },
  {
    "id": "wpn_5",
    "sourceFile": "daoqi.md",
    "name": "“韵缻”缶型导器",
    "category": "导器",
    "range": "近程",
    "company": "天工峡集团",
    "socialCredit": "?",
    "bonusSources": [
      "魅力",
      "智力"
    ],
    "rawDamage": "4d6，3级炼金",
    "damageType": "炼金",
    "armorPierceLevel": 3,
    "size": 25,
    "isHeavy": true,
    "isTwoHanded": false,
    "rarityMajor": "收藏级",
    "rarityMinor": "D",
    "price": 300,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": true,
    "rawValue": "收藏级D，300两"
  },
  {
    "id": "wpn_6",
    "sourceFile": "daoqi.md",
    "name": "万神都国际＆梵天武库",
    "category": "导器",
    "range": "远程",
    "company": "万神都国际＆梵天武库",
    "socialCredit": "？",
    "bonusSources": [
      "智力",
      "灵性",
      "魅力"
    ],
    "rawDamage": "6d6，4级温差",
    "damageType": "温差",
    "armorPierceLevel": 4,
    "size": 28,
    "isHeavy": true,
    "isTwoHanded": true,
    "rarityMajor": "收藏级",
    "rarityMinor": "C",
    "price": 1000,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": true,
    "rawValue": "收藏级C，1000两"
  },
  {
    "id": "wpn_7",
    "sourceFile": "daoqi.md",
    "name": "PB16 梅塔特隆 匣型导器",
    "category": "导器",
    "range": "近程",
    "company": "万神都国际＆梵天武库",
    "socialCredit": "？",
    "bonusSources": [
      "灵性",
      "魅力"
    ],
    "rawDamage": "5d4，2级温差",
    "damageType": "温差",
    "armorPierceLevel": 2,
    "size": 16,
    "isHeavy": false,
    "isTwoHanded": true,
    "rarityMajor": "收藏级",
    "rarityMinor": "D",
    "price": 350,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": true,
    "rawValue": "收藏级D，350两"
  },
  {
    "id": "wpn_8",
    "sourceFile": "daoqi.md",
    "name": "PB15 唯一点 匣型导器",
    "category": "导器",
    "range": "中程",
    "company": "万神都国际＆梵天武库",
    "socialCredit": "？",
    "bonusSources": [
      "灵性",
      "魅力"
    ],
    "rawDamage": "4d4，3级温差",
    "damageType": "温差",
    "armorPierceLevel": 3,
    "size": 15,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "收藏级",
    "rarityMinor": "D",
    "price": 350,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": true,
    "rawValue": "收藏级D，350两"
  },
  {
    "id": "wpn_9",
    "sourceFile": "daoqiZD.md",
    "name": "鬼方28式“般若”自动铳",
    "category": "自动导器",
    "range": "可自选（近程，中程，远程）",
    "company": "西川霊術重工株式会社",
    "socialCredit": "IV",
    "bonusSources": [
      "弹药",
      "智力"
    ],
    "rawDamage": "4d6，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 14,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "上品级",
    "rarityMinor": "A",
    "price": 250,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "上品级A，250两"
  },
  {
    "id": "wpn_10",
    "sourceFile": "daoqiZD.md",
    "name": "鬼方31式“抚子”狙击步枪",
    "category": "自动导器",
    "range": "远程",
    "company": "西川霊術重工株式会社",
    "socialCredit": "V",
    "bonusSources": [
      "弹药",
      "体术",
      "智力",
      "灵性"
    ],
    "rawDamage": "6d6，2级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 2,
    "size": 24,
    "isHeavy": true,
    "isTwoHanded": true,
    "rarityMajor": "收藏级",
    "rarityMinor": "C",
    "price": 400,
    "hasTactics": false,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "收藏级C，400两"
  },
  {
    "id": "wpn_11",
    "sourceFile": "daoqiZD.md",
    "name": "SN-17 “珍珠夜”充能精确铳",
    "category": "自动导器",
    "range": "远程",
    "company": "新血股份有限公司",
    "socialCredit": "V",
    "bonusSources": [
      "弹药",
      "知觉",
      "智力"
    ],
    "rawDamage": "3d10，2级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 2,
    "size": 24,
    "isHeavy": true,
    "isTwoHanded": true,
    "rarityMajor": "收藏级",
    "rarityMinor": "C",
    "price": 800,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "收藏级C，800两"
  },
  {
    "id": "wpn_12",
    "sourceFile": "daoqiZD.md",
    "name": "SN-22 “五月”充能连发短铳",
    "category": "自动导器",
    "range": "近程",
    "company": "新血股份有限公司",
    "socialCredit": "II",
    "bonusSources": [
      "弹药",
      "知觉"
    ],
    "rawDamage": "2d4，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 8,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "上品级",
    "rarityMinor": "C",
    "price": 100,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "上品级C，100两"
  },
  {
    "id": "wpn_13",
    "sourceFile": "daoqiZD.md",
    "name": "SN-30 “瓶”充能轨道炮",
    "category": "自动导器",
    "range": "中程",
    "company": "新血股份有限公司",
    "socialCredit": "?",
    "bonusSources": [
      "弹药"
    ],
    "rawDamage": "3d10，2级钝器",
    "damageType": "钝器",
    "armorPierceLevel": 2,
    "size": 26,
    "isHeavy": true,
    "isTwoHanded": false,
    "rarityMajor": "收藏级",
    "rarityMinor": "B",
    "price": 1200,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "收藏级B，1200两"
  },
  {
    "id": "wpn_14",
    "sourceFile": "daoqiZD.md",
    "name": "SN-46 “梣木”充能无臂弩",
    "category": "自动导器",
    "range": "中程",
    "company": "新血股份有限公司",
    "socialCredit": "?",
    "bonusSources": [
      "弹药"
    ],
    "rawDamage": "3d8，2级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 2,
    "size": 14,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "上品级",
    "rarityMinor": "A",
    "price": 250,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "上品级A，250两"
  },
  {
    "id": "wpn_15",
    "sourceFile": "daoqiZD.md",
    "name": "P33 点 短铳",
    "category": "自动导器",
    "range": "近程",
    "company": "万神都国际＆梵天武库",
    "socialCredit": "II",
    "bonusSources": [
      "弹药"
    ],
    "rawDamage": "2d6，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 4,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "商业级",
    "rarityMinor": "C",
    "price": 30,
    "hasTactics": false,
    "hasAccessories": true,
    "hasExtraEffect": false,
    "rawValue": "商业级C，30两"
  },
  {
    "id": "wpn_16",
    "sourceFile": "daoqiZD.md",
    "name": "P71亏格 目标射击短铳",
    "category": "自动导器",
    "range": "近程",
    "company": "万神都国际＆梵天武库",
    "socialCredit": "?",
    "bonusSources": [
      "弹药",
      "体术",
      "智力"
    ],
    "rawDamage": "2d6，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 6,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "商业级",
    "rarityMinor": "B",
    "price": 50,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "商业级B，50两"
  },
  {
    "id": "wpn_17",
    "sourceFile": "daoqiZD.md",
    "name": "M223卡宾 结 短型铳",
    "category": "自动导器",
    "range": "中程",
    "company": "万神都国际＆梵天武库",
    "socialCredit": "?",
    "bonusSources": [
      "弹药",
      "智力",
      "知觉"
    ],
    "rawDamage": "3d8，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 14,
    "isHeavy": false,
    "isTwoHanded": true,
    "rarityMajor": "上品级",
    "rarityMinor": "C",
    "price": 150,
    "hasTactics": false,
    "hasAccessories": true,
    "hasExtraEffect": false,
    "rawValue": "上品级C，150两"
  },
  {
    "id": "wpn_18",
    "sourceFile": "daoqiZD.md",
    "name": "M223A4卡宾 链 短型铳",
    "category": "自动导器",
    "range": "中程",
    "company": "万神都国际＆梵天武库",
    "socialCredit": "?",
    "bonusSources": [
      "弹药"
    ],
    "rawDamage": "3d8，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 12,
    "isHeavy": false,
    "isTwoHanded": true,
    "rarityMajor": "上品级",
    "rarityMinor": "C",
    "price": 150,
    "hasTactics": false,
    "hasAccessories": true,
    "hasExtraEffect": false,
    "rawValue": "上品级C，150两"
  },
  {
    "id": "wpn_19",
    "sourceFile": "daoqiZD.md",
    "name": "MK32“天火”大口径发射器",
    "category": "自动导器",
    "range": "近程",
    "company": "杰克＆威廉姆斯",
    "socialCredit": "?",
    "bonusSources": [
      "弹药",
      "体术",
      "体力",
      "知觉"
    ],
    "rawDamage": "3d8，2级钝器",
    "damageType": "钝器",
    "armorPierceLevel": 2,
    "size": 24,
    "isHeavy": true,
    "isTwoHanded": false,
    "rarityMajor": "收藏级",
    "rarityMinor": "B",
    "price": 1500,
    "hasTactics": false,
    "hasAccessories": true,
    "hasExtraEffect": false,
    "rawValue": "收藏级B，1500两"
  },
  {
    "id": "wpn_20",
    "sourceFile": "daoqiZD.md",
    "name": "库尼P110短铳",
    "category": "自动导器",
    "range": "近程",
    "company": "巴瓦克防务",
    "socialCredit": "?",
    "bonusSources": [
      "弹药",
      "智力",
      "灵性"
    ],
    "rawDamage": "2d8，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 4,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "商业级",
    "rarityMinor": "A",
    "price": 40,
    "hasTactics": false,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "商业级A，40两"
  },
  {
    "id": "wpn_21",
    "sourceFile": "daoqiZD.md",
    "name": "库尼P110-S短铳",
    "category": "自动导器",
    "range": "近程",
    "company": "巴瓦克防务",
    "socialCredit": "?",
    "bonusSources": [
      "弹药",
      "智力",
      "灵性"
    ],
    "rawDamage": "2d4，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 2,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "上品级",
    "rarityMinor": "C",
    "price": 100,
    "hasTactics": false,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "上品级C，100两"
  },
  {
    "id": "wpn_22",
    "sourceFile": "daoqiZD.md",
    "name": "阿卡基R340短型铳",
    "category": "自动导器",
    "range": "中程",
    "company": "巴瓦克防务",
    "socialCredit": "?",
    "bonusSources": [
      "弹药",
      "体术",
      "智力"
    ],
    "rawDamage": "4d8，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 14,
    "isHeavy": false,
    "isTwoHanded": true,
    "rarityMajor": "上品级",
    "rarityMinor": "A",
    "price": 200,
    "hasTactics": false,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "上品级A，200两"
  },
  {
    "id": "wpn_23",
    "sourceFile": "daoqiZD.md",
    "name": "阿卡基R390穿甲铳",
    "category": "自动导器",
    "range": "中程",
    "company": "巴瓦克防务",
    "socialCredit": "?",
    "bonusSources": [
      "弹药",
      "体术",
      "智力",
      "知觉"
    ],
    "rawDamage": "3d8，2级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 2,
    "size": 14,
    "isHeavy": false,
    "isTwoHanded": true,
    "rarityMajor": "收藏级",
    "rarityMinor": "D",
    "price": 400,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "收藏级D，400两"
  },
  {
    "id": "wpn_24",
    "sourceFile": "daoqiZD.md",
    "name": "迈利R110精确铳",
    "category": "自动导器",
    "range": "远程",
    "company": "巴瓦克防务",
    "socialCredit": "?",
    "bonusSources": [
      "弹药"
    ],
    "rawDamage": "3d12，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 18,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "收藏级",
    "rarityMinor": "C",
    "price": 600,
    "hasTactics": false,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "收藏级C，600两"
  },
  {
    "id": "wpn_29",
    "sourceFile": "weaponsDN.md",
    "name": "鬼方45式“暴鬼”四臂破城弓",
    "category": "动能兵械",
    "range": "远程",
    "company": "西川霊術重工株式会社",
    "socialCredit": "V",
    "bonusSources": [
      "弹药",
      "体术",
      "体力"
    ],
    "rawDamage": "4d12，2级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 2,
    "size": 30,
    "isHeavy": true,
    "isTwoHanded": true,
    "rarityMajor": "收藏级",
    "rarityMinor": "D",
    "price": 350,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "收藏级D，350两"
  },
  {
    "id": "wpn_30",
    "sourceFile": "weaponsDN.md",
    "name": "真君拐＆重楼棒（12拐，双鱼拐，阴阳拐，电狗＆杀威棒，电鞭，电棍，天干地支）",
    "category": "动能兵械",
    "range": "贴身",
    "company": "天工峡集团",
    "socialCredit": "？",
    "bonusSources": [
      "体术"
    ],
    "rawDamage": "2d10，2级钝器/以太",
    "damageType": "钝器/以太",
    "armorPierceLevel": 2,
    "size": 4,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "商业级",
    "rarityMinor": "B",
    "price": 25,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "商业级B，25两"
  },
  {
    "id": "wpn_31",
    "sourceFile": "weaponsDN.md",
    "name": "“穿杨”反曲轨道弓",
    "category": "动能兵械",
    "range": "近程",
    "company": "天工峡集团",
    "socialCredit": "？",
    "bonusSources": [
      "弹药",
      "体术",
      "知觉"
    ],
    "rawDamage": "3d6，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 8,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "商业级",
    "rarityMinor": "A",
    "price": 50,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "商业级A，50两"
  },
  {
    "id": "wpn_32",
    "sourceFile": "weaponsDN.md",
    "name": "“入木”复合轨道弓",
    "category": "动能兵械",
    "range": "近程",
    "company": "天工峡集团",
    "socialCredit": "？",
    "bonusSources": [
      "弹药",
      "体术",
      "知觉"
    ],
    "rawDamage": "3d6，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 10,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "上品级",
    "rarityMinor": "D",
    "price": 60,
    "hasTactics": true,
    "hasAccessories": true,
    "hasExtraEffect": false,
    "rawValue": "上品级D，60两"
  },
  {
    "id": "wpn_33",
    "sourceFile": "weaponsDN.md",
    "name": "“骏鹰”骑射短弓",
    "category": "动能兵械",
    "range": "近程",
    "company": "天工峡集团",
    "socialCredit": "？",
    "bonusSources": [
      "弹药",
      "体术",
      "知觉"
    ],
    "rawDamage": "2d6，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 4,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "上品级",
    "rarityMinor": "C",
    "price": 100,
    "hasTactics": false,
    "hasAccessories": false,
    "hasExtraEffect": true,
    "rawValue": "上品级C，100两（残壳状态需要额外1000两安装费用）"
  },
  {
    "id": "wpn_34",
    "sourceFile": "weaponsDN.md",
    "name": "“没羽”战术弹弓",
    "category": "动能兵械",
    "range": "近程",
    "company": "天工峡集团",
    "socialCredit": "？",
    "bonusSources": [
      "体术",
      "知觉"
    ],
    "rawDamage": "2d4，1级钝器",
    "damageType": "钝器",
    "armorPierceLevel": 1,
    "size": 4,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "商业级",
    "rarityMinor": "D",
    "price": 10,
    "hasTactics": false,
    "hasAccessories": false,
    "hasExtraEffect": true,
    "rawValue": "商业级D 10两"
  },
  {
    "id": "wpn_35",
    "sourceFile": "weaponsDN.md",
    "name": "C2 幂 折叠手弩",
    "category": "动能兵械",
    "range": "近程",
    "company": "万神都国际＆梵天武库",
    "socialCredit": "？",
    "bonusSources": [
      "弹药",
      "体术",
      "知觉"
    ],
    "rawDamage": "2d4，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 2,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "商业级",
    "rarityMinor": "B",
    "price": 50,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "商业级B，50两"
  },
  {
    "id": "wpn_36",
    "sourceFile": "weaponsZF.md",
    "name": "西部41（W-41）",
    "category": "自赋能兵械",
    "range": "近程",
    "company": "西川灵术重工株式会社",
    "socialCredit": "II",
    "bonusSources": [
      "弹药"
    ],
    "rawDamage": "3d4，1 级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": "",
    "size": 4,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "商业级",
    "rarityMinor": "B",
    "price": 30,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "商业级B，30两"
  },
  {
    "id": "wpn_37",
    "sourceFile": "weaponsZF.md",
    "name": "新新西部 41（NNW-41）",
    "category": "自赋能兵械",
    "range": "近程",
    "company": "西川灵术重工株式会社",
    "socialCredit": "II",
    "bonusSources": [
      "弹药"
    ],
    "rawDamage": "3d6，1 级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": "",
    "size": 4,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "商业级",
    "rarityMinor": "A",
    "price": 41,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "商业级A，41两"
  },
  {
    "id": "wpn_38",
    "sourceFile": "weaponsZF.md",
    "name": "鬼方30式“鵺”通用机枪",
    "category": "自赋能兵械",
    "range": "近程",
    "company": "西川灵术重工株式会社",
    "socialCredit": "VI",
    "bonusSources": [
      "弹药",
      "体力",
      "体术"
    ],
    "rawDamage": "7d6，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 30,
    "isHeavy": true,
    "isTwoHanded": true,
    "rarityMajor": "收藏级",
    "rarityMinor": "C",
    "price": 400,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "收藏级C，400两"
  },
  {
    "id": "wpn_39",
    "sourceFile": "weaponsZF.md",
    "name": "SN-2 “蕨”双管霰弹枪",
    "category": "自赋能兵械",
    "range": "近程",
    "company": "新血股份有限公司",
    "socialCredit": "II",
    "bonusSources": [
      "弹药"
    ],
    "rawDamage": "2d10，2级钝器",
    "damageType": "钝器",
    "armorPierceLevel": 2,
    "size": 10,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "商业级",
    "rarityMinor": "C",
    "price": 10,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "商业级C 10两"
  },
  {
    "id": "wpn_40",
    "sourceFile": "weaponsZF.md",
    "name": "SN-15 “粉彩”神射手步枪",
    "category": "自赋能兵械",
    "range": "中程",
    "company": "新血股份有限公司",
    "socialCredit": "IV",
    "bonusSources": [
      "弹药"
    ],
    "rawDamage": "2d12，2级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 2,
    "size": 12,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "上品级",
    "rarityMinor": "C",
    "price": 100,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "上品级C，100两"
  },
  {
    "id": "wpn_41",
    "sourceFile": "weaponsZF.md",
    "name": "“金刚”多臂重弩",
    "category": "自赋能兵械",
    "range": "远程",
    "company": "天工峡集团",
    "socialCredit": "?",
    "bonusSources": [
      "弹药"
    ],
    "rawDamage": "3d10，2级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 2,
    "size": 22,
    "isHeavy": true,
    "isTwoHanded": false,
    "rarityMajor": "上品级",
    "rarityMinor": "C",
    "price": 150,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "上品级C，150两"
  },
  {
    "id": "wpn_42",
    "sourceFile": "weaponsZF.md",
    "name": "“穿云”发条扭力重弩",
    "category": "自赋能兵械",
    "range": "远程",
    "company": "天工峡集团",
    "socialCredit": "?",
    "bonusSources": [
      "弹药"
    ],
    "rawDamage": "4d8，2级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 2,
    "size": 18,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "上品级",
    "rarityMinor": "C",
    "price": 150,
    "hasTactics": true,
    "hasAccessories": true,
    "hasExtraEffect": false,
    "rawValue": "上品级C，150两"
  },
  {
    "id": "wpn_43",
    "sourceFile": "weaponsZF.md",
    "name": "“卧龙”连发弩",
    "category": "自赋能兵械",
    "range": "近程",
    "company": "天工峡集团",
    "socialCredit": "?",
    "bonusSources": [
      "弹药"
    ],
    "rawDamage": "6d6，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 14,
    "isHeavy": false,
    "isTwoHanded": true,
    "rarityMajor": "上品级",
    "rarityMinor": "C",
    "price": 150,
    "hasTactics": false,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "上品级C，150两"
  },
  {
    "id": "wpn_44",
    "sourceFile": "weaponsZF.md",
    "name": "SMG151分形 冲锋枪",
    "category": "自赋能兵械",
    "range": "近程",
    "company": "万神都国际＆梵天武库",
    "socialCredit": "?",
    "bonusSources": [
      "弹药"
    ],
    "rawDamage": "5d4，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 12,
    "isHeavy": false,
    "isTwoHanded": true,
    "rarityMajor": "上品级",
    "rarityMinor": "C",
    "price": 100,
    "hasTactics": false,
    "hasAccessories": true,
    "hasExtraEffect": false,
    "rawValue": "上品级C，100两"
  },
  {
    "id": "wpn_45",
    "sourceFile": "weaponsZF.md",
    "name": "SMG151A1二维分形 冲锋枪",
    "category": "自赋能兵械",
    "range": "近程",
    "company": "万神都国际＆梵天武库",
    "socialCredit": "?",
    "bonusSources": [
      "弹药"
    ],
    "rawDamage": "5d4，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 10,
    "isHeavy": false,
    "isTwoHanded": true,
    "rarityMajor": "上品级",
    "rarityMinor": "C",
    "price": 120,
    "hasTactics": false,
    "hasAccessories": true,
    "hasExtraEffect": false,
    "rawValue": "上品级C，120两"
  },
  {
    "id": "wpn_46",
    "sourceFile": "weaponsZF.md",
    "name": "SMG151A3三维分形 冲锋枪",
    "category": "自赋能兵械",
    "range": "近程",
    "company": "万神都国际＆梵天武库",
    "socialCredit": "?",
    "bonusSources": [
      "弹药",
      "体术"
    ],
    "rawDamage": "4d4，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 12,
    "isHeavy": false,
    "isTwoHanded": true,
    "rarityMajor": "上品级",
    "rarityMinor": "C",
    "price": 120,
    "hasTactics": false,
    "hasAccessories": true,
    "hasExtraEffect": false,
    "rawValue": "上品级C，120两"
  },
  {
    "id": "wpn_47",
    "sourceFile": "weaponsZF.md",
    "name": "SG7 垂径 连发霰弹枪",
    "category": "自赋能兵械",
    "range": "近程",
    "company": "万神都国际＆梵天武库",
    "socialCredit": "?",
    "bonusSources": [
      "弹药",
      "体术",
      "灵性"
    ],
    "rawDamage": "3d6，2级钝器",
    "damageType": "钝器",
    "armorPierceLevel": 2,
    "size": 14,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "上品级",
    "rarityMinor": "D",
    "price": 100,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "上品级D，100两"
  },
  {
    "id": "wpn_48",
    "sourceFile": "weaponsZF.md",
    "name": "RC22 共弦 连发弩",
    "category": "自赋能兵械",
    "range": "近程",
    "company": "万神都国际＆梵天武库",
    "socialCredit": "?",
    "bonusSources": [
      "弹药"
    ],
    "rawDamage": "4d6，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 10,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "上品级",
    "rarityMinor": "D",
    "price": 100,
    "hasTactics": false,
    "hasAccessories": true,
    "hasExtraEffect": false,
    "rawValue": "上品级D，100两"
  },
  {
    "id": "wpn_49",
    "sourceFile": "weaponsZF.md",
    "name": "MK12“预备役”手枪",
    "category": "自赋能兵械",
    "range": "近程",
    "company": "杰克＆威廉姆斯",
    "socialCredit": "II",
    "bonusSources": [
      "弹药",
      "体术",
      "知觉"
    ],
    "rawDamage": "2d8，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 4,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "商业级",
    "rarityMinor": "A",
    "price": 40,
    "hasTactics": false,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "商业级A，40两"
  },
  {
    "id": "wpn_50",
    "sourceFile": "weaponsZF.md",
    "name": "MK12pro“民兵”手枪",
    "category": "自赋能兵械",
    "range": "近程",
    "company": "杰克＆威廉姆斯",
    "socialCredit": "?",
    "bonusSources": [
      "弹药"
    ],
    "rawDamage": "2d10，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 6,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "商业级",
    "rarityMinor": "A",
    "price": 50,
    "hasTactics": false,
    "hasAccessories": true,
    "hasExtraEffect": false,
    "rawValue": "商业级A，50两"
  },
  {
    "id": "wpn_51",
    "sourceFile": "weaponsZF.md",
    "name": "MK16“自由之子”冲锋手枪",
    "category": "自赋能兵械",
    "range": "近程",
    "company": "杰克＆威廉姆斯",
    "socialCredit": "?",
    "bonusSources": [
      "弹药"
    ],
    "rawDamage": "7d4，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 10,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "上品级",
    "rarityMinor": "C",
    "price": 100,
    "hasTactics": false,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "上品级C，100两"
  },
  {
    "id": "wpn_52",
    "sourceFile": "weaponsZF.md",
    "name": "MK18“轻骑兵”自动步枪",
    "category": "自赋能兵械",
    "range": "近程",
    "company": "杰克＆威廉姆斯",
    "socialCredit": "?",
    "bonusSources": [
      "弹药"
    ],
    "rawDamage": "5d6，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 14,
    "isHeavy": false,
    "isTwoHanded": true,
    "rarityMajor": "上品级",
    "rarityMinor": "A",
    "price": 250,
    "hasTactics": false,
    "hasAccessories": true,
    "hasExtraEffect": false,
    "rawValue": "上品级A，250两"
  },
  {
    "id": "wpn_53",
    "sourceFile": "weaponsZF.md",
    "name": "MK18-S“三头犬”半自动步枪",
    "category": "自赋能兵械",
    "range": "中程",
    "company": "杰克＆威廉姆斯",
    "socialCredit": "?",
    "bonusSources": [
      "弹药"
    ],
    "rawDamage": "4d6，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 12,
    "isHeavy": false,
    "isTwoHanded": true,
    "rarityMajor": "上品级",
    "rarityMinor": "A",
    "price": 200,
    "hasTactics": false,
    "hasAccessories": true,
    "hasExtraEffect": false,
    "rawValue": "上品级A，200两"
  },
  {
    "id": "wpn_54",
    "sourceFile": "weaponsZF.md",
    "name": "MK20“禁区宪兵”半自动狙击步枪",
    "category": "自赋能兵械",
    "range": "远程",
    "company": "杰克＆威廉姆斯",
    "socialCredit": "?",
    "bonusSources": [
      "弹药",
      "体术",
      "体力"
    ],
    "rawDamage": "3d10，2级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 2,
    "size": 20,
    "isHeavy": true,
    "isTwoHanded": true,
    "rarityMajor": "收藏级",
    "rarityMinor": "D",
    "price": 300,
    "hasTactics": false,
    "hasAccessories": true,
    "hasExtraEffect": false,
    "rawValue": "收藏级D，300两"
  },
  {
    "id": "wpn_55",
    "sourceFile": "weaponsZF.md",
    "name": "MK28“武装干涉”反器材狙击步枪",
    "category": "动能兵械",
    "range": "远程",
    "company": "杰克＆威廉姆斯",
    "socialCredit": "？",
    "bonusSources": [
      "弹药",
      "体术",
      "体力"
    ],
    "rawDamage": "5d10，2级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 2,
    "size": 30,
    "isHeavy": true,
    "isTwoHanded": true,
    "rarityMajor": "收藏级",
    "rarityMinor": "C",
    "price": 1000,
    "hasTactics": false,
    "hasAccessories": true,
    "hasExtraEffect": false,
    "rawValue": "收藏级C，1000两"
  },
  {
    "id": "wpn_56",
    "sourceFile": "weaponsZF.md",
    "name": "库尼SMG190连发铳",
    "category": "自赋能兵械",
    "range": "近程",
    "company": "巴瓦克防务",
    "socialCredit": "?",
    "bonusSources": [
      "弹药",
      "智力",
      "知觉"
    ],
    "rawDamage": "5d4，1级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 1,
    "size": 10,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "上品级",
    "rarityMinor": "C",
    "price": 100,
    "hasTactics": false,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "上品级C，100两"
  },
  {
    "id": "wpn_57",
    "sourceFile": "weaponsZF.md",
    "name": "库尼P230消音铳",
    "category": "自赋能兵械",
    "range": "近程",
    "company": "巴瓦克防务",
    "socialCredit": "?",
    "bonusSources": [
      "弹药",
      "体术",
      "魅力"
    ],
    "rawDamage": "1d8，2级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 2,
    "size": 4,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "上品级",
    "rarityMinor": "D",
    "price": 70,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "上品级D，70两"
  },
  {
    "id": "wpn_58",
    "sourceFile": "weaponsZF.md",
    "name": "索巴“大威力”左轮手枪",
    "category": "自赋能兵械",
    "range": "近程",
    "company": "巴瓦克防务",
    "socialCredit": "II",
    "bonusSources": [
      "弹药",
      "体术",
      "魅力"
    ],
    "rawDamage": "1d12，2级穿刺",
    "damageType": "穿刺",
    "armorPierceLevel": 2,
    "size": 6,
    "isHeavy": false,
    "isTwoHanded": false,
    "rarityMajor": "上品级",
    "rarityMinor": "C",
    "price": 100,
    "hasTactics": true,
    "hasAccessories": false,
    "hasExtraEffect": false,
    "rawValue": "上品级C 100两"
  }
];